//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Nullable<int> id { get; set; }
        public string name { get; set; }
        public string descriprion { get; set; }
        public string address { get; set; }
        public System.DateTime timestamp { get; set; }
        public int hallId { get; set; }
    
        public virtual Hall Hall { get; set; }
    }
}
