//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public int row { get; set; }
        public int column { get; set; }
        public int eventId { get; set; }
        public int userId { get; set; }
        public Nullable<int> classId { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual TicketClass TicketClass { get; set; }
        public virtual User User { get; set; }
    }
}
