//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircusApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int skillId { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual User User { get; set; }
    }
}
